[tool.poetry]
name = "open-pki"
version = "0.1.0"
description = "A Django app to create and manage certificates"
authors = ["Sander Bos <mail@sanderbos.net>"]
readme = "README.md"
repository = "https://github.com/bossan/openpki"
keywords = ["pki", "django"]
packages = [{ include = "pki", from = "src" }]


[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2"
cryptography = "^40.0.2"
daphne = "^4.0.0"
psycopg2 = "^2.9.6"
python-decouple = "^3.8"
whitenoise = "^6.4.0"


[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
