[tool.poetry]
name = "open-pki"
version = "0.3.5"
description = "A Django app to create and manage certificates"
authors = ["Sander Bos <mail@sanderbos.net>"]
readme = "README.md"
repository = "https://github.com/bossan/openpki"
keywords = ["pki", "django"]
packages = [{ include = "pki", from = "src" }]

[tool.poetry.dependencies]
python = "^3.9"
django = "^4.2"
cryptography = "^42.0.3"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.0.0"
bandit = "^1.7.7"
vulture = "^2.11"

[tool.bandit]
exclude_dirs = [
    'tests',
    'migrations',
    'venv',
]

[tool.vulture]
exclude = ['migrations']
min_confidence = 100

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
