# Generated by Django 4.1.7 on 2023-03-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0010_remove_user_site_siteuser'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='siteuser',
            unique_together={('user', 'site')},
        ),
    ]
