# Generated by Django 4.1.7 on 2023-04-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0012_alter_siteuser_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientCertificate',
            new_name='Certificate',
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
    ]
