# Generated by Django 4.2.1 on 2023-05-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='ssid',
        ),
    ]
