# Generated by Django 4.2.1 on 2023-05-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0002_remove_site_ssid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='export_password',
        ),
    ]
