# Generated by Django 4.1.7 on 2023-03-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0003_clientcertificate_usercertificate_delete_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcertificate',
            name='dns_name',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='clientcertificate',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
