# Generated by Django 4.1.7 on 2023-03-23 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0008_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateauthority',
            name='site',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='site_%(class)s', to='pki.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientcertificate',
            name='site',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='site_%(class)s', to='pki.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='pki.site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='site',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='site_%(class)s', to='pki.site'),
            preserve_default=False,
        ),
    ]
