# Generated by Django 4.2 on 2023-04-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0013_rename_clientcertificate_certificate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
